no-interactsh: true
disable-update-check: true

exclude-tags:
  - dos
  - bruteforce

exclude-templates:
  - http/cves/2019/CVE-2019-14696.yaml
  - http/cves/2021/CVE-2021-28164.yaml
  - http/fuzzing/wordpress-themes-detect.yaml
  - http/fuzzing/mdb-database-file.yaml
  - http/fuzzing/iis-shortname.yaml
  - dns/soa-detect.yaml
  - javascript/enumeration/pop3/pop3-capabilities-enum.yaml
  - javascript/enumeration/redis/redis-require-auth.yaml
  - dast/vulnerabilities/sqli/time-based-sqli.yaml
  - javascript/enumeration/minecraft-enum.yaml
  - javascript/enumeration/minecraft-enum.yaml
