no-interactsh: true
disable-update-check: true

include-tags:
  - cve
  - dast
  - headless
  - ssl
  - http

exclude-tags:
  - dos
  - local
  - cloud
  - file
  - c2
  - fortinet
  - audit
  - dns
  - network
  - token-spray
  - takeover
  - osint
  - honeypot
  - cnvd
  - creds-stuffing
  # container infra
  - k8s
  - kubernetes
  - docker
  - harbor
  - registry
  # dbs
  - mysql
  - mssql
  - postgres
  - postgresql
  - redis
  - mongodb
  - couchdb
  # devices / IoT / network appliances
  - iot
  - router
  - camera
  - nas
  - dvr
  - vpn
  - firewall
  - waf

exclude-templates:
  - http/cves/2019/CVE-2019-14696.yaml
  - http/cves/2021/CVE-2021-28164.yaml
  - http/fuzzing/wordpress-themes-detect.yaml
  - http/fuzzing/mdb-database-file.yaml
  - http/fuzzing/iis-shortname.yaml
  - dns/soa-detect.yaml
  - javascript/enumeration/pop3/pop3-capabilities-enum.yaml
  - javascript/enumeration/redis/redis-require-auth.yaml
  - dast/vulnerabilities/sqli/time-based-sqli.yaml
  - javascript/enumeration/minecraft-enum.yaml
  - javascript/enumeration/minecraft-enum.yaml
  - headless/extract-urls.yaml
  - headless/screenshot.yaml
